- name: test
  hosts: all
  vars:
    line: "2021-09-29T00:56:58.097940Z 6 [Note] [MY-010454] [Server] A temporary password is generated for root@localhost: p>-lrpQlT1op"
    user_name: Chuk
  tasks:
  - name: extract password
    set_fact:
      # var greetings = "My name is ..."
      greetings: "My name is {{ user_name }}"
      default_password: "{{ line.split(':')[-1] | trim }}"

  - name: Line
    debug:
      msg: "{{ line }}"
  - name: Echo greetings
    debug:
      msg: "{{ default_password }}"
